#103143 Suspend the Zaak when a recovery period starts
valtimo-platform/valtimo-backend-libraries pull request #1238
Opened 2024-02-26 14:08 UTC by Klaas-Ritense

2024-02-28 11:25 UTC, theo-ritense approved these changes

2024-02-28 11:28 UTC, theo-ritense requested changes, later dismissed
Comments on [PR 1235](https://github.com/valtimo-platform/valtimo-backend-libraries/pull/1235) are still pending

2024-02-29 15:43 UTC, ivo-ritense submitted a review, later dismissed

2024-03-01 07:51 UTC, theo-ritense approved these changes

2024-03-01 08:06 UTC, merged