Feature/109672 create on start validation
valtimo-platform/valtimo-backend-libraries pull request #1336
Opened 2024-05-06 05:32 UTC by laurens-ritense

2024-05-07 06:26 UTC, sirolf2009 requested changes

2024-05-07 06:26 UTC, sirolf2009 commented on form-view-model/src/main/kotlin/com/ritense/formviewmodel/domain/validation/OnStartUpViewModelValidator.kt
> +                throw IllegalArgumentException("ViewModelLoader ${viewModelLoader.javaClass.simpleName} is not valid for form ${viewModelLoader.getFormName()}!")
Can you add to the message which keys were a mismatch?

2024-05-07 08:34 UTC, Tom-Ritense requested changes

2024-05-07 08:34 UTC, Tom-Ritense commented on form-view-model/src/main/kotlin/com/ritense/formviewmodel/domain/validation/FormDefinitionPrefixedKeysExtractor.kt
> +
remove newline

2024-05-07 08:34 UTC, Tom-Ritense commented on form-view-model/src/main/kotlin/com/ritense/formviewmodel/domain/validation/FormDefinitionPrefixedKeysExtractor.kt
> +            it["key"].asText().contains(PREFIX)
remove dub "key"

2024-05-07 08:34 UTC, Tom-Ritense commented on form-view-model/src/main/kotlin/com/ritense/formviewmodel/domain/validation/OnStartUpViewModelValidator.kt
> +@Component
remove component

2024-05-07 08:34 UTC, Tom-Ritense commented on form-view-model/src/main/kotlin/com/ritense/formviewmodel/autoconfigure/FormViewModelAutoConfiguration.kt
> +        context: ApplicationContext
use same approach as commandHandling like
 fun commandDispatcher(handlers: List<CommandHandler<*, *>>): CommandDispatcher {

2024-05-07 08:34 UTC, Tom-Ritense commented on form-view-model/src/main/kotlin/com/ritense/formviewmodel/autoconfigure/FormViewModelAutoConfiguration.kt
> +    @Order(Ordered.LOWEST_PRECEDENCE)
order can go

2024-05-07 08:34 UTC, Tom-Ritense commented on form-view-model/src/main/kotlin/com/ritense/formviewmodel/domain/validation/ClassPropertyExtractor.kt
> +class ClassPropertyExtractor {
ViewModel.extractProperties() is my suggestion. Extension function in kotlin i mean give it a try

2024-05-07 08:34 UTC, Tom-Ritense commented on form-view-model/src/main/kotlin/com/ritense/formviewmodel/domain/validation/FormDefinitionPrefixedKeysExtractor.kt
> +class FormDefinitionPrefixedKeysExtractor {
rename to ....ViewModelKeysExtractor

2024-05-07 08:34 UTC, Tom-Ritense commented on form-view-model/src/main/kotlin/com/ritense/formviewmodel/domain/validation/OnStartUpViewModelValidator.kt
> +    private val context: ApplicationContext,
refactor

2024-05-07 08:34 UTC, Tom-Ritense commented on form-view-model/src/main/kotlin/com/ritense/formviewmodel/domain/validation/OnStartUpViewModelValidator.kt
> +) : ApplicationRunner {
I like it

2024-05-07 08:34 UTC, Tom-Ritense commented on form-view-model/src/main/kotlin/com/ritense/formviewmodel/domain/validation/OnStartUpViewModelValidator.kt
> +                throw IllegalArgumentException("ViewModelLoader ${viewModelLoader.javaClass.simpleName} is not valid for form ${viewModelLoader.getFormName()}!")
This should be really clear what is wrong. Also combine ALL errors in one list.

2024-05-07 08:34 UTC, Tom-Ritense commented on form-view-model/src/main/kotlin/com/ritense/formviewmodel/web/rest/FormViewModelResource.kt
> +            parseViewModel(formViewModel, viewModelLoaderFactory.getViewModelLoader(formName)?.getViewModelType()!!).update()
!! seems a code smell type optional?

2024-05-07 08:34 UTC, Tom-Ritense commented on form-view-model/src/main/kotlin/com/ritense/formviewmodel/web/rest/FormViewModelResource.kt
> +            viewModelLoaderFactory.getViewModelLoader(formName)?.onLoad(taskInstanceId)
rename to load

2024-05-13 14:16 UTC, closed without merging

2024-05-13 14:16 UTC, Tom-Ritense commented
old