The liveness and readiness endpoints can be accessed without authentication
valtimo-platform/valtimo-backend-libraries pull request #1527
Opened 2024-08-28 19:19 UTC by erik-ritense

The liveness and readiness endpoints can be accessed without authentication when the following property is set: `managment.endpoint.health.show-details=never`

### Describe the changes
Link to the related Github issue: 

**Relevant comments:**
> 

### Breaking changes

- [x ] The contribution only contains changes that are not breaking.

### Documentation

- [x] Release notes have been written for these changes. 

Link to the pull request in the [Valtimo documentation repository](https://github.com/valtimo-platform/valtimo-documentation): https://github.com/valtimo-platform/valtimo-documentation/pull/737
>

New features or changes that have been introduced have been documented.
- [ ] Yes
- [x] Not applicable

### Tests
Unit tests have been added that cover these changes
- [ ] Yes
- [x] Not applicable

Integration tests have been added that cover these changes
- [ ] Yes
- [x] Not applicable

### Security
The [Secure by Default principle](https://en.wikipedia.org/wiki/Secure_by_default) has been applied to these changes
- [x] Yes
- [ ] Not applicable

Added or changed REST API endpoints have authentication and authorization in place
- [ ] Yes
- [x] Not applicable

Valtimo access control checks have been implemented
- [ ] Yes
- [x] Not applicable

### Dependencies
Newly added dependencies do not introduce known vulnerabilities/CVE's and are in line with the Valtimo license
- [ ] Yes
- [x] Not applicable

2024-08-29 06:00 UTC, erik-ritense commented
The changes from this PR are applicable (and can be tested) when these properties are set:
```
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
```

2024-08-29 11:54 UTC, ivo-ritense approved these changes

2024-08-29 11:57 UTC, marijnritense requested changes
Going to put this on request changes as an on-hold status; Will discuss this with security people early next week and get back to you.

2024-09-10 13:30 UTC, theo-ritense commented
@erik-ritense 
There is a check for the /health endpoint that makes sure that the endpoint is only open when the details are not shown (`never`), or the logged in user has the role `ROLE_ACTUATOR`.

This check should also be done on the groups (liveness and readiness).
For more information, please check [here](https://medium.com/@salarai.de/how-to-enable-liveness-and-readiness-probes-in-a-spring-boot-application-a40cf3423db3) and `HealthEndpointProperties.Group`

2025-01-04 09:11 UTC, closed without merging