Feature/30525 openzaak to connector
valtimo-platform/valtimo-backend-libraries pull request #38
Opened 2021-12-03 14:56 UTC by Rick-Ritense

Not the final version

2021-12-27 10:44 UTC, Klaas-Ritense commented on connector/src/main/kotlin/com/ritense/connector/domain/ConnectorType.kt
> +    var allowMultipleConnectorInstances: Boolean = true
Bij het opstarten krijg ik deze error:
```
Null value was assigned to a property [class com.ritense.connector.domain.ConnectorType.allowMultipleConnectorInstances] of primitive type setter of com.ritense.connector.domain.ConnectorType.allowMultipleConnectorInstances
```
Ik ga m zelf fixen

2021-12-27 12:15 UTC, Klaas-Ritense approved these changes

2021-12-27 12:28 UTC, Klaas-Ritense requested changes
Ziet er goed uit. Alleen het migratie script nog

2021-12-27 12:28 UTC, Klaas-Ritense commented on connector/src/main/kotlin/com/ritense/connector/domain/ConnectorType.kt
> +    var allowMultipleConnectorInstances: Boolean = true
hmm, misschien had ik dit niet moeten fixen. Aangezien je nog bezig bent met het migratie script

2022-01-03 10:17 UTC, Rick-Ritense commented on connector/src/main/kotlin/com/ritense/connector/domain/ConnectorType.kt
> +    var allowMultipleConnectorInstances: Boolean = true
oh apart  ... ik ga er naar kijken

2022-01-05 10:13 UTC, marijnritense approved these changes

2022-01-05 11:24 UTC, closed without merging

2022-01-05 11:24 UTC, Rick-Ritense commented
Closed PR because Github required a re-review from @Klaas-Ritense who is not at work currently