Fixed download for resources stored in openzaak documenten API
valtimo-platform/valtimo-backend-libraries pull request #41
Opened 2021-12-07 08:40 UTC by ivo-ritense

2021-12-07 10:36 UTC, Rick-Ritense approved these changes

2021-12-07 12:11 UTC, Klaas-Ritense requested changes

2021-12-08 15:23 UTC, ivo-ritense commented on openzaak/src/main/kotlin/com/ritense/openzaak/service/impl/DocumentenService.kt
> +        //TODO: kijken of streamen mogelijk is
De bedoeling was inderdaad om dit later nog eens te doen. Maar ik heb besloten om dat niet in de vorm van een TODO comment te doen. Verwijderd.

2021-12-09 08:59 UTC, Klaas-Ritense approved these changes

2021-12-09 12:16 UTC, merged

2022-01-27 20:46 UTC, Hildebrand-Ritense commented
@ivo-ritense is er een reden dat deze PR direct op main is gemaakt in plaats van development?